version: "3.9"
   
services:
  frontend:
    build:
        context: vueapp
    restart: always
    stdin_open: true
    environment:
        - CHOKIDAR_USEPOLLING=true
    links:
        - "web:web"
    ports:
        - "80:8080" 
    volumes:
        - './vueapp:/app:delegated'
        # - '/frontend/node_modulesc'
        - '/app/node_modules'
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    env_file:
        - ./.env
    depends_on:
            - db
    volumes:
      - .:/code
    ports:
      - "8000:8000"
  db:
    image: mysql:latest
    env_file:
        - ./.env
    #restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    volumes:
        - mysql-volume:/var/lib/mysql
        - ../logs:/var/log/mysql
        - ./override-mysql:/etc/mysql/mysql.conf.d
    ports:
        - "3306:3306"
volumes:
  mysql-volume:
  logs-volume: